---
- name: Configure security checklist on server
  hosts: amberdb
  become: yes
  vars_files:
    - vars/passwords.yml
  vars: 
    - ADMIN: amber
  handlers:
    - name: restart fail2ban
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - fail2ban
        - firewalld

    - name: restart sshd
      service:
        name: sshd
        state: restarted

  tasks:
    - name: create admin user
      user:
        name: "{{ ADMIN }}"
        state: present
        shell: /bin/bash
        password: "{{ admin_password | password_hash('sha512') }}"

    - name: Create admin user's sudoers file
      copy:
        dest: "/etc/sudoers.d/{{ ADMIN }}"
        content: "{{ ADMIN }} ALL=(ALL) NOPASSWD: ALL"
        owner: root
        group: root

    - name: update sshd config to disallow root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: PermitRootLogin yes
        line: PermitRootLogin no
        state: present
      notify: restart sshd

    - name: Install fail2ban and things
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - fail2ban
        - vim
        - bash-completion

    - name: Enable and start fail2ban
      service:
        name: fail2ban
        state: started
        enabled: true

    - name: copy config file for fail2ban
      command: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

    - name: enable sshd jail
      lineinfile:
        path: /etc/fail2ban/jail.local
        regexp: '[sshd]'
        line: enabled = true
        insertafter: '[sshd]'
      notify: restart fail2ban

    - name: Check that fail2ban has sshd jail enabled
      command: fail2ban-client status
      register: fail2ban_client

    - name: Show fail2ban result
      debug:
        var: fail2ban_client
